# Generated by Django 4.0.4 on 2022-05-10 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='Account ID')),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_wpm', models.FloatField(verbose_name='Raw WPM')),
                ('wpm', models.IntegerField(verbose_name='WPM')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pietype.account')),
            ],
        ),
    ]
