# Generated by Django 4.0.4 on 2022-05-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pietype', '0002_alter_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Date'),
        ),
    ]
