# Generated by Django 4.0.4 on 2022-05-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pietype', '0003_attempt_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='sentence',
            field=models.CharField(default='null', max_length=200, verbose_name='Sentence'),
        ),
    ]
