# Generated by Django 4.0.4 on 2022-05-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pietype', '0005_remove_attempt_account_attempt_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='sentence',
            field=models.JSONField(verbose_name='Sentence'),
        ),
    ]
